-- Bono fase de grupos: conserva los puntos de semifinalista/finalista que cada jugador
-- ya tenia en el ranking antes de la correccion del bug de premios prematuros.
-- Montos tomados del backup backup_bd/polla_futbolera_backup.sql (3 jul 2026, fila BONUSES).
-- Idempotente: se puede ejecutar mas de una vez sin duplicar puntos.
BEGIN;
INSERT INTO prediction_scores (user_id, source_type, source_id, points, breakdown) VALUES (9, 'GROUP_PHASE_BONUS', 0, 10, '{"groupPhaseBonus": 10}'::jsonb) ON CONFLICT (user_id, source_type, source_id) DO UPDATE SET points = EXCLUDED.points, breakdown = EXCLUDED.breakdown, updated_at = NOW(); -- Felipe Florez
INSERT INTO prediction_scores (user_id, source_type, source_id, points, breakdown) VALUES (10, 'GROUP_PHASE_BONUS', 0, 10, '{"groupPhaseBonus": 10}'::jsonb) ON CONFLICT (user_id, source_type, source_id) DO UPDATE SET points = EXCLUDED.points, breakdown = EXCLUDED.breakdown, updated_at = NOW(); -- Andres Cardona
INSERT INTO prediction_scores (user_id, source_type, source_id, points, breakdown) VALUES (11, 'GROUP_PHASE_BONUS', 0, 10, '{"groupPhaseBonus": 10}'::jsonb) ON CONFLICT (user_id, source_type, source_id) DO UPDATE SET points = EXCLUDED.points, breakdown = EXCLUDED.breakdown, updated_at = NOW(); -- Christian Diseño
INSERT INTO prediction_scores (user_id, source_type, source_id, points, breakdown) VALUES (12, 'GROUP_PHASE_BONUS', 0, 10, '{"groupPhaseBonus": 10}'::jsonb) ON CONFLICT (user_id, source_type, source_id) DO UPDATE SET points = EXCLUDED.points, breakdown = EXCLUDED.breakdown, updated_at = NOW(); -- Leche
INSERT INTO prediction_scores (user_id, source_type, source_id, points, breakdown) VALUES (13, 'GROUP_PHASE_BONUS', 0, 20, '{"groupPhaseBonus": 20}'::jsonb) ON CONFLICT (user_id, source_type, source_id) DO UPDATE SET points = EXCLUDED.points, breakdown = EXCLUDED.breakdown, updated_at = NOW(); -- Julian trejos
INSERT INTO prediction_scores (user_id, source_type, source_id, points, breakdown) VALUES (14, 'GROUP_PHASE_BONUS', 0, 20, '{"groupPhaseBonus": 20}'::jsonb) ON CONFLICT (user_id, source_type, source_id) DO UPDATE SET points = EXCLUDED.points, breakdown = EXCLUDED.breakdown, updated_at = NOW(); -- Jhon velez
INSERT INTO prediction_scores (user_id, source_type, source_id, points, breakdown) VALUES (15, 'GROUP_PHASE_BONUS', 0, 20, '{"groupPhaseBonus": 20}'::jsonb) ON CONFLICT (user_id, source_type, source_id) DO UPDATE SET points = EXCLUDED.points, breakdown = EXCLUDED.breakdown, updated_at = NOW(); -- Jorge zuleta
INSERT INTO prediction_scores (user_id, source_type, source_id, points, breakdown) VALUES (23, 'GROUP_PHASE_BONUS', 0, 10, '{"groupPhaseBonus": 10}'::jsonb) ON CONFLICT (user_id, source_type, source_id) DO UPDATE SET points = EXCLUDED.points, breakdown = EXCLUDED.breakdown, updated_at = NOW(); -- Marlon Valencia
INSERT INTO prediction_scores (user_id, source_type, source_id, points, breakdown) VALUES (24, 'GROUP_PHASE_BONUS', 0, 20, '{"groupPhaseBonus": 20}'::jsonb) ON CONFLICT (user_id, source_type, source_id) DO UPDATE SET points = EXCLUDED.points, breakdown = EXCLUDED.breakdown, updated_at = NOW(); -- Mario Duque
INSERT INTO prediction_scores (user_id, source_type, source_id, points, breakdown) VALUES (25, 'GROUP_PHASE_BONUS', 0, 20, '{"groupPhaseBonus": 20}'::jsonb) ON CONFLICT (user_id, source_type, source_id) DO UPDATE SET points = EXCLUDED.points, breakdown = EXCLUDED.breakdown, updated_at = NOW(); -- Camilo Rodriguez
INSERT INTO prediction_scores (user_id, source_type, source_id, points, breakdown) VALUES (26, 'GROUP_PHASE_BONUS', 0, 10, '{"groupPhaseBonus": 10}'::jsonb) ON CONFLICT (user_id, source_type, source_id) DO UPDATE SET points = EXCLUDED.points, breakdown = EXCLUDED.breakdown, updated_at = NOW(); -- Felipe Gómez
INSERT INTO prediction_scores (user_id, source_type, source_id, points, breakdown) VALUES (27, 'GROUP_PHASE_BONUS', 0, 20, '{"groupPhaseBonus": 20}'::jsonb) ON CONFLICT (user_id, source_type, source_id) DO UPDATE SET points = EXCLUDED.points, breakdown = EXCLUDED.breakdown, updated_at = NOW(); -- Andrés Ospina
INSERT INTO prediction_scores (user_id, source_type, source_id, points, breakdown) VALUES (28, 'GROUP_PHASE_BONUS', 0, 10, '{"groupPhaseBonus": 10}'::jsonb) ON CONFLICT (user_id, source_type, source_id) DO UPDATE SET points = EXCLUDED.points, breakdown = EXCLUDED.breakdown, updated_at = NOW(); -- Felipe Leal
INSERT INTO prediction_scores (user_id, source_type, source_id, points, breakdown) VALUES (30, 'GROUP_PHASE_BONUS', 0, 10, '{"groupPhaseBonus": 10}'::jsonb) ON CONFLICT (user_id, source_type, source_id) DO UPDATE SET points = EXCLUDED.points, breakdown = EXCLUDED.breakdown, updated_at = NOW(); -- Valeria toro
INSERT INTO prediction_scores (user_id, source_type, source_id, points, breakdown) VALUES (31, 'GROUP_PHASE_BONUS', 0, 20, '{"groupPhaseBonus": 20}'::jsonb) ON CONFLICT (user_id, source_type, source_id) DO UPDATE SET points = EXCLUDED.points, breakdown = EXCLUDED.breakdown, updated_at = NOW(); -- Wilson murillo
INSERT INTO prediction_scores (user_id, source_type, source_id, points, breakdown) VALUES (32, 'GROUP_PHASE_BONUS', 0, 20, '{"groupPhaseBonus": 20}'::jsonb) ON CONFLICT (user_id, source_type, source_id) DO UPDATE SET points = EXCLUDED.points, breakdown = EXCLUDED.breakdown, updated_at = NOW(); -- Norma henao
INSERT INTO prediction_scores (user_id, source_type, source_id, points, breakdown) VALUES (33, 'GROUP_PHASE_BONUS', 0, 20, '{"groupPhaseBonus": 20}'::jsonb) ON CONFLICT (user_id, source_type, source_id) DO UPDATE SET points = EXCLUDED.points, breakdown = EXCLUDED.breakdown, updated_at = NOW(); -- Sebastián garzon
INSERT INTO prediction_scores (user_id, source_type, source_id, points, breakdown) VALUES (34, 'GROUP_PHASE_BONUS', 0, 10, '{"groupPhaseBonus": 10}'::jsonb) ON CONFLICT (user_id, source_type, source_id) DO UPDATE SET points = EXCLUDED.points, breakdown = EXCLUDED.breakdown, updated_at = NOW(); -- John Escobar
INSERT INTO prediction_scores (user_id, source_type, source_id, points, breakdown) VALUES (35, 'GROUP_PHASE_BONUS', 0, 20, '{"groupPhaseBonus": 20}'::jsonb) ON CONFLICT (user_id, source_type, source_id) DO UPDATE SET points = EXCLUDED.points, breakdown = EXCLUDED.breakdown, updated_at = NOW(); -- Anderson Duque Baena
INSERT INTO prediction_scores (user_id, source_type, source_id, points, breakdown) VALUES (37, 'GROUP_PHASE_BONUS', 0, 10, '{"groupPhaseBonus": 10}'::jsonb) ON CONFLICT (user_id, source_type, source_id) DO UPDATE SET points = EXCLUDED.points, breakdown = EXCLUDED.breakdown, updated_at = NOW(); -- José garcia
INSERT INTO prediction_scores (user_id, source_type, source_id, points, breakdown) VALUES (38, 'GROUP_PHASE_BONUS', 0, 20, '{"groupPhaseBonus": 20}'::jsonb) ON CONFLICT (user_id, source_type, source_id) DO UPDATE SET points = EXCLUDED.points, breakdown = EXCLUDED.breakdown, updated_at = NOW(); -- Nora Lucia
INSERT INTO prediction_scores (user_id, source_type, source_id, points, breakdown) VALUES (41, 'GROUP_PHASE_BONUS', 0, 10, '{"groupPhaseBonus": 10}'::jsonb) ON CONFLICT (user_id, source_type, source_id) DO UPDATE SET points = EXCLUDED.points, breakdown = EXCLUDED.breakdown, updated_at = NOW(); -- Lorena Grisales
INSERT INTO prediction_scores (user_id, source_type, source_id, points, breakdown) VALUES (42, 'GROUP_PHASE_BONUS', 0, 20, '{"groupPhaseBonus": 20}'::jsonb) ON CONFLICT (user_id, source_type, source_id) DO UPDATE SET points = EXCLUDED.points, breakdown = EXCLUDED.breakdown, updated_at = NOW(); -- Luis Fernando Paez
INSERT INTO prediction_scores (user_id, source_type, source_id, points, breakdown) VALUES (43, 'GROUP_PHASE_BONUS', 0, 20, '{"groupPhaseBonus": 20}'::jsonb) ON CONFLICT (user_id, source_type, source_id) DO UPDATE SET points = EXCLUDED.points, breakdown = EXCLUDED.breakdown, updated_at = NOW(); -- Bryan Alexis Murcia Bocanegra
INSERT INTO prediction_scores (user_id, source_type, source_id, points, breakdown) VALUES (45, 'GROUP_PHASE_BONUS', 0, 20, '{"groupPhaseBonus": 20}'::jsonb) ON CONFLICT (user_id, source_type, source_id) DO UPDATE SET points = EXCLUDED.points, breakdown = EXCLUDED.breakdown, updated_at = NOW(); -- Diana Vera
INSERT INTO prediction_scores (user_id, source_type, source_id, points, breakdown) VALUES (46, 'GROUP_PHASE_BONUS', 0, 10, '{"groupPhaseBonus": 10}'::jsonb) ON CONFLICT (user_id, source_type, source_id) DO UPDATE SET points = EXCLUDED.points, breakdown = EXCLUDED.breakdown, updated_at = NOW(); -- Mateo pineda
INSERT INTO prediction_scores (user_id, source_type, source_id, points, breakdown) VALUES (47, 'GROUP_PHASE_BONUS', 0, 20, '{"groupPhaseBonus": 20}'::jsonb) ON CONFLICT (user_id, source_type, source_id) DO UPDATE SET points = EXCLUDED.points, breakdown = EXCLUDED.breakdown, updated_at = NOW(); -- Julio Garzon
INSERT INTO prediction_scores (user_id, source_type, source_id, points, breakdown) VALUES (48, 'GROUP_PHASE_BONUS', 0, 10, '{"groupPhaseBonus": 10}'::jsonb) ON CONFLICT (user_id, source_type, source_id) DO UPDATE SET points = EXCLUDED.points, breakdown = EXCLUDED.breakdown, updated_at = NOW(); -- Edilberto Bañol
INSERT INTO prediction_scores (user_id, source_type, source_id, points, breakdown) VALUES (50, 'GROUP_PHASE_BONUS', 0, 20, '{"groupPhaseBonus": 20}'::jsonb) ON CONFLICT (user_id, source_type, source_id) DO UPDATE SET points = EXCLUDED.points, breakdown = EXCLUDED.breakdown, updated_at = NOW(); -- Eliana Osorio
INSERT INTO prediction_scores (user_id, source_type, source_id, points, breakdown) VALUES (51, 'GROUP_PHASE_BONUS', 0, 20, '{"groupPhaseBonus": 20}'::jsonb) ON CONFLICT (user_id, source_type, source_id) DO UPDATE SET points = EXCLUDED.points, breakdown = EXCLUDED.breakdown, updated_at = NOW(); -- Samuel Naranjo
INSERT INTO prediction_scores (user_id, source_type, source_id, points, breakdown) VALUES (54, 'GROUP_PHASE_BONUS', 0, 10, '{"groupPhaseBonus": 10}'::jsonb) ON CONFLICT (user_id, source_type, source_id) DO UPDATE SET points = EXCLUDED.points, breakdown = EXCLUDED.breakdown, updated_at = NOW(); -- Alejandro Henao
INSERT INTO prediction_scores (user_id, source_type, source_id, points, breakdown) VALUES (55, 'GROUP_PHASE_BONUS', 0, 20, '{"groupPhaseBonus": 20}'::jsonb) ON CONFLICT (user_id, source_type, source_id) DO UPDATE SET points = EXCLUDED.points, breakdown = EXCLUDED.breakdown, updated_at = NOW(); -- Angela ortiz
INSERT INTO prediction_scores (user_id, source_type, source_id, points, breakdown) VALUES (56, 'GROUP_PHASE_BONUS', 0, 10, '{"groupPhaseBonus": 10}'::jsonb) ON CONFLICT (user_id, source_type, source_id) DO UPDATE SET points = EXCLUDED.points, breakdown = EXCLUDED.breakdown, updated_at = NOW(); -- Laura María Arango
INSERT INTO prediction_scores (user_id, source_type, source_id, points, breakdown) VALUES (58, 'GROUP_PHASE_BONUS', 0, 10, '{"groupPhaseBonus": 10}'::jsonb) ON CONFLICT (user_id, source_type, source_id) DO UPDATE SET points = EXCLUDED.points, breakdown = EXCLUDED.breakdown, updated_at = NOW(); -- Diana Arango
INSERT INTO prediction_scores (user_id, source_type, source_id, points, breakdown) VALUES (59, 'GROUP_PHASE_BONUS', 0, 10, '{"groupPhaseBonus": 10}'::jsonb) ON CONFLICT (user_id, source_type, source_id) DO UPDATE SET points = EXCLUDED.points, breakdown = EXCLUDED.breakdown, updated_at = NOW(); -- Daniela Amaya
INSERT INTO prediction_scores (user_id, source_type, source_id, points, breakdown) VALUES (66, 'GROUP_PHASE_BONUS', 0, 10, '{"groupPhaseBonus": 10}'::jsonb) ON CONFLICT (user_id, source_type, source_id) DO UPDATE SET points = EXCLUDED.points, breakdown = EXCLUDED.breakdown, updated_at = NOW(); -- Pablo garzon
INSERT INTO prediction_scores (user_id, source_type, source_id, points, breakdown) VALUES (68, 'GROUP_PHASE_BONUS', 0, 10, '{"groupPhaseBonus": 10}'::jsonb) ON CONFLICT (user_id, source_type, source_id) DO UPDATE SET points = EXCLUDED.points, breakdown = EXCLUDED.breakdown, updated_at = NOW(); -- Daniel Parra
COMMIT;
